services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - "5175:5175"

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"
